add checks for -t

diff --git a/mysqlchk_iptables b/mysqlchk_iptables
--- a/mysqlchk_iptables
+++ b/mysqlchk_iptables
@@ -37,8 +37,8 @@ while true ; do
     -d|--daemon) DAEMON="1" ; shift ;;
     -x|--stop) STOP="1" ; shift ;;
     -s|--status) STATUS="1"; shift ;;
-    -u|--user) MYSQL_USERNAME2="$2" ; shift 2 ;;
-    -p|--password) MYSQL_PASSWORD2="$2" ; shift 2 ;;
+    -u|--user) MYSQL_USERNAME="$2" ; shift 2 ;;
+    -p|--password) MYSQL_PASSWORD="$2" ; shift 2 ;;
     -l|--log-file) LOG_FILE="$2" ; shift 2 ;;
     -e|--defaults-extra-file) DEFAULTS_EXTRA_FILE="$2"; shift 2 ;;
     -a|--source-address) SOURCE_ADDRESS="$2"; shift 2 ;;
@@ -144,8 +144,15 @@ main()
         2>${ERR_FILE} | tail -1 2>>${ERR_FILE})
 
     if [[ "$DRYRUN" == "1" ]]; then
-      echo "wsrep_local_state: $WSREP_STATUS"
-      echo "wsrep_sst_method: $WSREP_SST"
+        if [[ -z "$WSREP_STATUS" && -z "$WSREP_SST" ]]; then
+            echo "Unable to detect wsrep_local_state and wsrep_sst_method. Something wasn't right."
+            echo "Please check user/password. Ensure those are correct. Aborting."
+            exit 1
+        else
+            echo "Detected variables/status:"
+            echo "wsrep_local_state: $WSREP_STATUS"
+            echo "wsrep_sst_method: $WSREP_SST"
+        fi
     fi
 
     if [[ "${WSREP_STATUS}" == "4" ]] || [[ "${WSREP_STATUS}" == "2" && "${WSREP_SST}" =~ "xtrabackup" ]]
@@ -154,7 +161,7 @@ main()
         if [[ $AVAILABLE_WHEN_READONLY -eq 0 ]];then
             READ_ONLY=$($MYSQL_CMDLINE -e "SHOW GLOBAL VARIABLES LIKE 'read_only';" \
                         2>${ERR_FILE} | tail -1 2>>${ERR_FILE})
-            [[ "$DRYRUN" == "1" ]] && echo "read_only: $READ_ONLY"
+            [[ "$DRYRUN" == "1" ]] && echo "read_only: $READ_ONLY" && echo ""
             if [[ "${READ_ONLY}" == "ON" ]];then
                 # Galera Cluster node local state is 'Synced', but it is in
                 # read-only mode.
